### PR TITLE
Remove duplicate content on curriculum page

### LINKED ISSUE #335: Curriculum page content
LEARNING IS SO MUCH MORE THAN A CURRICULUM AND SOME EDUCATIONAL MATERIALS. We currently use a mixture of workshops, exercises, projects, classroom break-out sessions and end-of-week challenges to help our students understand programming.

is the same content as

We believe that learning to code consists of much more than just the materials we provide and the curriculum we have created. We currently use a mixture of workshops, exercises, projects, classroom break-out sessions and end-of-week challenges to help our students understand programming.

---

We should probably remove the second paragraph on that page or change the content totally. Duplicating content is not good for SEO nor it is visually not useful :)

### PR DESCRIPTION
**Pull request by nikeshashar**
Change %span to %h4 and changed article-centered to article only. 
Visually QA'd with @jordanpoulton 
Closes #335

### CODE REVIEW

**Comment by spike01** [comment]
This looks so much better. :+1:

:ship:

**Comment by nikeshashar** [comment]
Squirrel me

**Comment by spike01** [comment]
:shipit:

**Comment by nikeshashar** [comment]
Boom! - Deployed

**Pull request merged**
