### PR TITLE
Adds deprecated browser warning for <= IE8

### LINKED ISSUE #292: Make website IE8 compatible or show a message
spike [3:30 PM] 
iexplore in all of its glorious forms only accounts for 5.57% of our traffic

spike [3:32 PM]
of which 25% of that traffic is from IE8 and below

spike [3:33 PM]
which is 1.39% of total site traffic. if we think it’s worth probably about a week of engineering work to support IE8, please let us know in the next sprint kick off.

evgeny [4:55 PM] 
@arfah: what’s the conversion rate of visits to applications?

ruben [4:56 PM] 
All should be on the metrics MD @evgeny

evgeny [5:00 PM] 
Thanks. So, it’s around 0.35. Then 3000 will translate into 10 applications, which will will translate into about 2 students, which will bring around 15-20k in revenue (fee + placement). Sounds like it’s worth a week’s of work?

### PR DESCRIPTION
**Pull request by ptolemybarnes**
Closes #292 
image

There's no button to hide the banner. Is that something we want?

### CODE REVIEW

**Comment by spike01** [comment]
https://css-tricks.com/how-to-create-an-ie-only-stylesheet/

Either hide everything except the banner or find someway of making the site part digestible?

Also - less shouty

**Comment by ptolemybarnes** [comment]
image

How's that?

**Comment by pitchinvasion** [comment]
@sjmog does this pass muster?

**Comment by spike01** [comment]
@sjmog can we get your visual opinion on this? I'm trying to clear out our columns...

**Pull request merged**
